# file: postgresql/tasks/extensions/extra_packages.yml

# keys
- name: PostgreSQL | Extensions | Add repo keys | apt
  apt_key:
    id: "{{ item.value.id }}"
    url: "{{ item.value.url }}"
    state: present
    keyring: /etc/apt/trusted.gpg.d/{{ item.value.id }}.gpg
  loop: "{{ postgresql_ext_extra_packages.apt_keys | default({}) | dict2items  }}"
  when: ansible_os_family == "Debian"

# repositories
- name: PostgreSQL | Extensions | Add repos | apt
  apt_repository:
    repo: "{{ item.value }}"
    state: present
  loop: "{{ postgresql_ext_extra_packages.apt_repositories | default({}) | dict2items }}"
  when: ansible_os_family == "Debian"
- name: PostgreSQL | Extensions | Add repos | RHEL
  yum_repository:
    name: "{{ item.value.name }}"
    description: "{{ item.value.description }}"
    baseurl: "{{ item.value.url }}"
    gpgkey: "{{ item.value.gpgkey }}"
    enabled: yes
  loop: "{{ postgresql_ext_extra_packages.yum_repositories | default({}) | dict2items }}"
  when: ansible_os_family == "RedHat"

# packages
- name: PostgreSQL | Extensions | Add packages | apt
  apt:
    name: "{{ postgresql_ext_extra_packages.names }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
  when: ansible_os_family == "Debian"
- name: PostgreSQL | Extensions | Add packages | RHEL
  yum:
    name: "{{ postgresql_ext_extra_packages.names }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"
