# file: postgresql/tasks/install_yum.yml

# The standard ca-certs are needed because  without them yum will fail to
# validate www.postgresql.org (or probably any other source).

  - block:
      - name: PostgreSQL | Install all the required dependencies (yum) | RHEL
        yum:
          name: "{{ postgresql_packages }}"
          state: present
          update_cache: yes

      - name: PostgreSQL | Add PostgreSQL repository | RHEL
        yum_repository:
           name: postgresql
           description: postgresql yum repo
           baseurl: "{{ postgresql_yum_repository_baseurl }}"
           gpgkey: "{{ postgresql_yum_repository_gpgkey }}"
           enabled: yes
        when: postgresql_install_repository

      - name: PostgreSQL | Disable postgresql module (necessary for RHEL8+)
        command:
          cmd: dnf module disable postgresql -y
        when: "ansible_distribution_major_version == '8' or ansible_distribution_major_version == '9'"
        register: disable_postgresql_module
        changed_when:
          - "disable_postgresql_module.rc == 0"
          - "'Disabling modules:\\n postgresql' in disable_postgresql_module.stdout"

      - name: PostgreSQL | Install PostgreSQL | RHEL
        yum:
          name:
            - "postgresql{{ postgresql_version_terse }}-server"
            - "postgresql{{ postgresql_version_terse }}"
            - "postgresql{{ postgresql_version_terse }}-contrib"
          state: present
          update_cache: yes
        environment: "{{ postgresql_env }}"

      - name: PostgreSQL | Setup service users profile | RHEL
        template:
          src: pgsql_profile.j2
          dest: "~{{ postgresql_service_user }}/.pgsql_profile"
          owner: "{{ postgresql_service_user }}"
          group: "{{ postgresql_service_group }}"
          mode: 0700
        when: postgresql_service_user_pgsql_profile

      - name: PostgreSQL | Create ~/pgtab.example | RHEL
        template:
          src: pgtab.j2
          dest: "~{{ postgresql_service_user }}/pgtab.example"
          owner: "{{ postgresql_service_user }}"
          group: "{{ postgresql_service_group }}"
          mode: 0644
        when: postgresql_service_user_pgsql_profile

      - name: PostgreSQL | Create ~/pgtab header | RHEL
        lineinfile:
          path: "~{{ postgresql_service_user }}/pgtab"
          owner: "{{ postgresql_service_user }}"
          group: "{{ postgresql_service_group }}"
          mode: 0644
          create: yes
          insertbefore: BOF
          regexp: "^#  pgclustername :.*$"
          line: "#  pgclustername : pgtabversion : pgrelease : pgport : pgdatabase : pgroot : pgbindir : [pgdata] : [pgwalarch] : [pgbackups]"
        when: postgresql_service_user_pgsql_profile

      - name: PostgreSQL | Create ~/pgtab Ansible warning | RHEL
        lineinfile:
          path: "~{{ postgresql_service_user }}/pgtab"
          owner: "{{ postgresql_service_user }}"
          group: "{{ postgresql_service_group }}"
          mode: 0644
          insertbefore: BOF
          regexp: "^#  NOTICE: This file is managed by Ansible. Do not modify it.$"
          line: "#  NOTICE: This file is managed by Ansible. Do not modify it."
        when: postgresql_service_user_pgsql_profile

      - name: PostgreSQL | Add database to ~/pgtab | RHEL
        lineinfile:
          path: "~{{ postgresql_service_user }}/pgtab"
          owner: "{{ postgresql_service_user }}"
          group: "{{ postgresql_service_group }}"
          mode: 0644
          regexp: "{{ postgresql_cluster_name }}:.*$"
          line: "{{ postgresql_cluster_name }}:1:{{ postgresql_version }}:{{ postgresql_port }}:{{ postgresql_service_user }}:/var/lib/pgsql:/usr/pgsql-{{ postgresql_version }}/bin:{{ postgresql_data_directory }}:::"
        when: postgresql_service_user_pgsql_profile

      - name: PostgreSQL | PGTune | RHEL
        yum:
          name: pgtune
          state: present
        environment: "{{ postgresql_env }}"
        when: postgresql_pgtune
