# file: postgresql/tasks/install.yml

- name: PostgreSQL | Add PostgreSQL repository apt-key
  apt_key:
    id: "{{ postgresql_apt_key_id }}"
    url: "{{ postgresql_apt_key_url }}"
    state: present
  when: postgresql_apt_key_url and postgresql_apt_key_id

- name: PostgreSQL | Add PostgreSQL repository
  apt_repository:
    repo: "{{ postgresql_apt_repository }}"
    state: present
  when: postgresql_apt_repository

- name: PostgreSQL | Make sure the dependencies are installed
  apt:
    pkg: "{{item}}"
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  with_items: ["python-psycopg2", "python-pycurl"]

- name: PostgreSQL | Install PostgreSQL
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  environment: postgresql_env
  with_items:
    - "postgresql-{{postgresql_version}}"
    - "postgresql-client-{{postgresql_version}}"
    - "postgresql-contrib-{{postgresql_version}}"
