# file: postgresql/tasks/install_dnf.yml

# The standard ca-certs are needed because  without them dnf will fail to
# validate www.postgresql.org (or probably any other source).

  - block:
      - name: PostgrSQL | Install all the required depedencies | dnf
        dnf:
          name: "ca-certificates, python-pycurl, glibc-common,libselinux-python"
          state: present

      - name: PostgreSQL | Add yum Repository | dnf
        yum_repository:
          name: postgresql
          state: present
          description: postgresql yum repo
          baseurl: "{{ postgresql_dnf_repository_baseurl }}"
          gpgkey: "{{ postgresql_dnf_repository_gpgkey }}"
        when: postgresql_install_repository

      - name: PostgreSQL | Install PostgreSQL | dnf
        dnf:
          name: "postgresql{{ postgresql_version_terse }}-server,postgresql{{ postgresql_version_terse }},postgresql{{ postgresql_version_terse }}-contrib"
          state: present
        environment: "{{ postgresql_env }}"

      - name: PostgreSQL | PGTune | dnf
        dnf:
          name: pgtune
          state: present
        environment: "{{ postgresql_env }}"
        when: postgresql_pgtune
