---
# file: postgresql/tasks/users.yml

- name: PostgreSQL | Ensure PostgreSQL is running
  service:
    name: "{{ postgresql_service_name }}"
    state: started

# Install 'acl' package to avoid a known issue with Ansible 2.1 and postgresql_user (https://github.com/ANXS/postgresql/issues/188)
- name: install acl | Debian
  package:
    pkg: "{{ item }}"
    update_cache: true
    cache_valid_time: 86400
    state: present
  with_items:
    - acl
  when: ansible_os_family == "Debian"

- name: PostgreSQL | Make sure the PostgreSQL users are present
  postgresql_user:
    name: "{{item.name}}"
    password: "{{ item.pass | default(omit) }}"
    encrypted: "{{ item.encrypted | default(omit) }}"
    port: "{{postgresql_port}}"
    state: present
    login_user: "{{postgresql_admin_user}}"
  no_log: true
  become: true
  become_user: "{{postgresql_admin_user}}"
  with_items: "{{postgresql_users}}"
  when: postgresql_users|length > 0
